config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/profskipulag/ST540103:
      branch: main
      repo: https://github.com/profskipulag/ST540103
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/profskipulag/ST540103 git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-chocolate-bandicoot.sh
        container: qc.acc_trippy-ivory-setter
  QC.Doc:
    repos:
      github.com/profskipulag/ST540103 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-wisteria-vulture.sh
        container: qc.doc_scaly-copper-ant
      github.com/profskipulag/ST540103 git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-fuchsia-eleuth.sh
        container: qc.doc_lumpy-asparagus-tamarin
      github.com/profskipulag/ST540103 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-carmine-alligator.sh
        container: qc.doc_zippy-auburn-ostrich
  QC.Lic:
    repos:
      github.com/profskipulag/ST540103 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-jade-mammoth.sh
        container: qc.lic_muzzy-burgundy-devil
  QC.Sec:
    repos:
      github.com/profskipulag/ST540103 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-seashell-peccary.sh
        container: qc.sec_clammy-aquamarine-tarantula
  QC.Sty:
    repos:
      github.com/profskipulag/ST540103 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-vermilion-giraffe.sh
        container: qc.sty_geeky-orange-donkey
  QC.Uni:
    repos:
      github.com/profskipulag/ST540103 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-amaranth-civet.sh
        container: qc.uni_nerdy-corn-zebu
  QC.Ver:
    repos:
      github.com/profskipulag/ST540103 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pear-antelope.sh
        container: qc.ver_pretty-rust-rhinoceros
timeout: 5400
